baseURL = 'https://packebusch.github.io/willkommen-in-magdeburg/'
languageCode = 'de-de'
title = 'Dokumentation rechter Gewalt in Magdeburg'

[params]
  description = "Dokumentation verifizierter Vorfälle rechter Gewalt in Magdeburg" 