name: News Monitor

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-22.04
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4 requests openai

      - name: Run news monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Checking OpenAI API key..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi
          python .github/scripts/monitor_news.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --name-only | grep -q "data/incidents.json"; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: monitor
    if: needs.monitor.outputs.changes_detected == 'true'
    uses: ./.github/workflows/hugo-deploy.yml 